### ISSUE TITLE
Menu Jitter when scrolling in Safari

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-unwind#73]
A user has reported menu jitter when scrolling in the latest version of Safari. Andrew has stated he's been able to replicate this.

You can replicate this issue on [the demo site](https://demo.siteorigin.com/unwind/).

**Comment by Misplon** [comment]
@adiraomj I'm keen to get another Unwind update out on Monday. Any chance you'll have time to check this out at the weekend? If not, we can ask Greg if he can dive in.

**Comment by Mukhammadali** [comment]
Hi guys, i installed your unwind theme. Firstly thank you very much for this kind of free source. But I should inform you about the bug when i  accessed my wbesite on mobile devices, Mobile device original browsers and other browsers such as Chrome, Firefox are also showing some bugs in the theme when i clicked on the menu button , after opening menu there are my pages and menu sections, there the number of cart menus are increasing and decreasing and when i clicked on the electronics menu arrow to open sub menu under it sub menu is automatically opening and closing in seconds after trying 3 4 times it is working. and this bug is always happening. I thought problem maybe with my confguration on my wordpress. but i tested this on the demo on your siteorigin website and the same bug also exists there. I checked in seveeral mobile devices by different manufacturers and it happens with all of them. So can you check it out and fix that or make some instructions to fix . I uploaded some screenshots below. Thanks in advance

![screenshot_2017-02-04-05-53-16](https://cloud.githubusercontent.com/assets/22298895/22608213/f860360e-ea9e-11e6-945b-4bbe6a3eeaec.png)
![screenshot_2017-02-04-05-53-20](https://cloud.githubusercontent.com/assets/22298895/22608215/fc1b96a8-ea9e-11e6-90b4-5dbc5a40b10e.png)

**Comment by AlexGStapleton** [comment]
This is related to siteorigin/siteorigin-north#142

**Comment by Misplon** [comment]
Cool, should be solved then. Thanks Alex.

**Comment by thabasti** [comment]
Hello :)

I just want to inform you that the menu jitter while scrolling in safari is not fixed. I am not a programmer, but I think it was exactly the same problem with north theme some time ago (https://github.com/siteorigin/siteorigin-north/issues/142) and @adiraomj did solve this issue with less js dependent sticky nav (https://github.com/siteorigin/siteorigin-north/pull/144). 

I really hope you guys can fix this for me and all the other safari users. thank you!

**Comment by Misplon** [comment]
Resolved in #127. Will push update shortly.
